client_homepage:
    path:     /home
    defaults: { _controller: ClientBundle:connect:authentification }

Add_Client:
    path:     /add
    defaults: { _controller: ClientBundle:Default:add }

Add_Agent:
    path:     /ajoutAgn
    defaults: { _controller: ClientBundle:Default:addAgent }

login_Agent:
    path:     /logagent
    defaults: { _controller: ClientBundle:Default:LogAgent }

check_Agent:
    path:     /checkagnet
    defaults: { _controller: ClientBundle:Default:checkAgent }

Add_Directeur:
    path:     /ajoutDir
    defaults: { _controller: ClientBundle:Default:addDir }

login_Directeur:
    path:     /logdir
    defaults: { _controller: ClientBundle:Default:LogDir }

check_Directeur:
    path:     /checkdir
    defaults: { _controller: ClientBundle:Default:checkDir }

Connect_Client:
    path:     /connect
    defaults: { _controller: ClientBundle:connect:connect }

Liste_Client:
    path:     /liste
    defaults: { _controller: ClientBundle:connect:listeClients }