client_homepage:
    path:     /home
    defaults: { _controller: ClientBundle:Default:index }

Add_Client:
    path:     /add
    defaults: { _controller: ClientBundle:Default:add }

Connect_Client:
    path:     /connect
    defaults: { _controller: ClientBundle:connect:connect }