credit:
    resource: "@CreditBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /client

app:
    resource: '@AppBundle/Controller/'
    type: annotation
