<?php

namespace ClientBundle\Repository;

/**
 * AgentCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
