<?php

namespace ClientBundle\Repository;

/**
 * DirecteurAgnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirecteurAgnRepository extends \Doctrine\ORM\EntityRepository
{
}
