<?php

namespace CreditBundle\Repository;

/**
 * CreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCreditID(){
        return $this->getEntityManager()->createQuery(
            "SELECT max(c.idCredit) FROM CreditBundle:Credit c"
        )
            ->setMaxResults(1)->getOneOrNullResult();
    }

    public function getCreditAgent()
    {
        return $this->getEntityManager()->createQuery(
            "select cl.nomCli,cl.prenomCli,cr.montantCredit,cr.dureeCredit,cr.interetCredit,p.nomProduit,cr.idCredit
                    from CreditBundle:Credit cr, ClientBundle:client cl, CreditBundle:produit p
                    where cl.idCli=cr.idClient and p.idProduit=cr.idProduit
                    and cr.approuveAgent = 0 and cr.etatCredit=1"
        )
            ->getArrayResult();
    }

    public function getCreditApprouve()
    {
        return $this->getEntityManager()->createQuery(
            "select cl.nomCli,cl.prenomCli,cr.montantCredit,cr.dureeCredit,cr.interetCredit,p.nomProduit,cr.idCredit
                    from CreditBundle:Credit cr, ClientBundle:client cl, CreditBundle:produit p
                    where cl.idCli=cr.idClient and p.idProduit=cr.idProduit
                    and cr.approuveAgent = 1"
        )
            ->getArrayResult();
    }

    public function getCreditAnnule()
    {
        return $this->getEntityManager()->createQuery(
            "select cl.nomCli,cl.prenomCli,cr.montantCredit,cr.dureeCredit,cr.interetCredit,p.nomProduit,cr.idCredit
                    from CreditBundle:Credit cr, ClientBundle:client cl, CreditBundle:produit p
                    where cl.idCli=cr.idClient and p.idProduit=cr.idProduit
                    and cr.etatCredit=0"
        )
            ->getArrayResult();
    }
}
