<?php

namespace CreditBundle\Repository;

/**
 * CreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCreditID(){
        return $this->getEntityManager()->createQuery(
            "SELECT max(c.idCredit) FROM CreditBundle:Credit c"
        )
            ->setMaxResults(1)->getOneOrNullResult();
    }
}
