<?php

namespace CreditBundle\Repository;

/**
 * EcheancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcheancierRepository extends \Doctrine\ORM\EntityRepository
{
}
