credit_homepage:
    path:     /
    defaults: { _controller: CreditBundle:Default:index }

Ajouter_Credit:
    path:     /ajouter
    defaults: { _controller: CreditBundle:Credit:Ajout }

Liste_Credit:
    path:     /liste
    defaults: { _controller: CreditBundle:Default:listeCredit }
